# fly.toml app configuration file generated for bchouse on 2023-11-01T16:09:55-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bchouse"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]

[env]
  BCHOUSE_URL="https://bchouse-site.fly.dev/"
  PAYGATE_URL="https://bchouse-pay.fly.dev/"
  UMBRACO_URL="https://bchouse-cms.fly.dev/"
  TYPESENSE_URL="https://bchouse-search.fly.dev"
  TYPESENSE_PUBLIC_URL="https://bchouse-search.fly.dev"
  CHAINGRAPH_WS_URL="wss://gql.chaingraph.pat.mn/v1/graphql"
  CHAINGRAPH_HTTP_URL="https://gql.chaingraph.pat.mn/v1/graphql"
  BCH_NETWORK="mainnet"
  SNOWFLAKE_EPOCH="1712438887"
  SNOWFLAKE_WORKER_ID="0"
  INNGEST_BRANCH="production"
  STORAGE_PATH_STYLE="false"
  STORAGE_API_URL="https://nyc3.digitaloceanspaces.com"
  STORAGE_PUBLIC_URL="https://nyc3.digitaloceanspaces.com"
  STORAGE_BUCKET="flipstarters"
  STORAGE_REGION="us-east-1"
  WALLET_CONNECT_PROJECT_ID="af5124b50e42ae55ac385eeb207d9a7a"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/healthcheck"
    protocol = "http"
    tls_skip_verify = false

[[metrics]]
  port = 8081
  path = "/metrics"
