# fly.toml app configuration file generated for bchouse-staging-cms-sqlserver on 2024-04-28T15:08:36-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bchouse-cms-sqlserver'
primary_region = 'iad'

[build]
  image = 'mcr.microsoft.com/mssql/server:2022-latest'

[env]
  ACCEPT_EULA = 'Y'
  MSSQL_PID = 'Developer'

[[mounts]]
  source = 'mssql_data'
  destination = '/var/opt/mssql'

[[services]]
  internal_port = 1433
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services.ports]]
  port = "1433" 

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
