name: E2E Testing
on:
  workflow_run:
    workflows: ['Staging Deploy']
    types:
      - completed
jobs:
  e2e:
    environment: staging
    name: E2E Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install PNPM
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm --filter @bchouse/e2e install
      - name: Install Playwright Browsers
        run: pnpm --filter @bchouse/e2e exec playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm --filter @bchouse/e2e exec playwright test
        env:
          NODE_ENV: 'development'
          BCHOUSE_URL: ${{ vars.BCHOUSE_STAGING_URL }}
          PAYGATE_URL: ${{ vars.PAYGATE_STAGING_URL }}
          UMBRACO_URL: ${{ vars.UMBRACO_STAGING_URL }}
          E2E_TEST_USERNAME: ${{ vars.E2E_TEST_USERNAME }}
          E2E_TEST_USER_BCH_ADDRESS: ${{ vars.E2E_TEST_USER_BCH_ADDRESS }}
          E2E_TEST_USER_PASSWORD: ${{ secrets.E2E_TEST_USER_PASSWORD }}
